### ISSUE TITLE
No module named 'blog/urls'

### ISSUE THREAD

**Issue by omer-ege-ozkaya** [omer-ege-ozkaya/bounswe573-2022#11]
```
% python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/*****/opt/anaconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/*****/opt/anaconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/*****/Documents/bogazici/semester_2/swe573-software-development-practice/bounswe573-2022/basic-web-application-creation/djangogirls/myenv/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/*****/Documents/bogazici/semester_2/swe573-software-development-practice/bounswe573-2022/basic-web-application-creation/djangogirls/myenv/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/Users/*****/Documents/bogazici/semester_2/swe573-software-development-practice/bounswe573-2022/basic-web-application-creation/djangogirls/myenv/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/Users/*****/Documents/bogazici/semester_2/swe573-software-development-practice/bounswe573-2022/basic-web-application-creation/djangogirls/myenv/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/Users/*****/Documents/bogazici/semester_2/swe573-software-development-practice/bounswe573-2022/basic-web-application-creation/djangogirls/myenv/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/Users/*****/Documents/bogazici/semester_2/swe573-software-development-practice/bounswe573-2022/basic-web-application-creation/djangogirls/myenv/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/Users/*****/Documents/bogazici/semester_2/swe573-software-development-practice/bounswe573-2022/basic-web-application-creation/djangogirls/myenv/lib/python3.8/site-packages/django/urls/resolvers.py", line 416, in check
    for pattern in self.url_patterns:
  File "/Users/*****/Documents/bogazici/semester_2/swe573-software-development-practice/bounswe573-2022/basic-web-application-creation/djangogirls/myenv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/*****/Documents/bogazici/semester_2/swe573-software-development-practice/bounswe573-2022/basic-web-application-creation/djangogirls/myenv/lib/python3.8/site-packages/django/urls/resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/*****/Documents/bogazici/semester_2/swe573-software-development-practice/bounswe573-2022/basic-web-application-creation/djangogirls/myenv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/*****/Documents/bogazici/semester_2/swe573-software-development-practice/bounswe573-2022/basic-web-application-creation/djangogirls/myenv/lib/python3.8/site-packages/django/urls/resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/*****/opt/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/*****/Documents/bogazici/semester_2/swe573-software-development-practice/bounswe573-2022/basic-web-application-creation/djangogirls/mysite/urls.py", line 21, in <module>
    path('', include('blog/urls')),
  File "/Users/*****/Documents/bogazici/semester_2/swe573-software-development-practice/bounswe573-2022/basic-web-application-creation/djangogirls/myenv/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/Users/*****/opt/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'blog/urls'
```

**Comment by omer-ege-ozkaya** [comment]
"blog/urls" is wrong. The correct address is "blog.urls"
